# Generated by Django 3.2.16 on 2022-12-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tags'),
        ('coverages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coverage',
            options={'ordering': ('published_at',)},
        ),
        migrations.AddField(
            model_name='coverage',
            name='published_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coverage',
            name='tag',
            field=models.ManyToManyField(to='home.Tags'),
        ),
    ]
