# Generated by Django 3.2.16 on 2023-05-13 07:21

from django.db import migrations, models
import django.db.models.deletion
from datetime import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0001_initial'),
        ('coverages', '0003_alter_coverage_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverage',
            name='published_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='publisher.publisher'),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now()),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coverage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.now()),
            preserve_default=False,
        ),
    ]
