# Generated by Django 3.2.13 on 2022-05-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='snippet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
