# Generated by Django 3.2.16 on 2022-12-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tags'),
        ('articles', '0003_auto_20221023_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='home.Tags'),
        ),
    ]
