# Generated by Django 3.2.16 on 2022-12-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tags'),
        ('articles', '0005_auto_20221215_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, to='home.Tags'),
        ),
    ]
