# Generated by Django 3.2.16 on 2023-05-07 18:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0001_initial'),
        ('articles', '0006_alter_article_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='publisher.publisher'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 5, 7, 18, 59, 22, 230239)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2023, 5, 7, 18, 59, 36, 680473)),
            preserve_default=False,
        ),
    ]
