# Generated by Django 3.2.16 on 2023-05-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20230507_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='number_of_visits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='source_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
