# Generated by Django 3.2.16 on 2023-10-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20230514_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('0', 'مقالة'), ('1', 'تغطية'), ('2', 'تدوينة حرة'), ('3', 'تحقيق')], default=0, max_length=3, verbose_name='type of article'),
        ),
    ]
