# Generated by Django 3.2.16 on 2023-12-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_article_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('0', 'مقالة'), ('1', 'تغطية'), ('2', 'تدوينة حرة'), ('3', 'تحقيق مكتوب'), ('4', 'وثائقي'), ('5', 'تحقيق فيديو')], default=0, max_length=3, verbose_name='type of article'),
        ),
    ]
