# Generated by Django 3.2.16 on 2023-12-10 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0001_initial'),
        ('articles', '0012_article_show_on_home_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='images/articles'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_on',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='publisher.publisher'),
        ),
        migrations.AlterField(
            model_name='article',
            name='snippet',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='source_link',
            field=models.URLField(null=True),
        ),
    ]
