# Generated by Django 3.2.16 on 2023-05-07 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0003_alter_investigation_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 5, 7, 18, 1, 39, 615729)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investigation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2023, 5, 7, 18, 1, 47, 928585)),
            preserve_default=False,
        ),
    ]
