# Generated by Django 3.2.16 on 2023-05-13 07:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_auto_20230513_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
    ]
