# Generated by Django 3.2.16 on 2023-05-13 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0004_alter_podcast_episode_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='episode_title',
            new_name='title',
        ),
    ]
