# Generated by Django 3.2.16 on 2023-10-15 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0007_podcast_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='video',
        ),
    ]
