# Generated by Django 3.2.16 on 2023-12-04 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prize',
            old_name='name',
            new_name='title',
        ),
    ]
