# Generated by Django 3.2.16 on 2023-12-10 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0001_initial'),
        ('prizes', '0002_rename_name_prize_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='published_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='prize',
            name='published_on',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='publisher.publisher'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='source_link',
            field=models.URLField(null=True),
        ),
    ]
