# Generated by Django 3.2.13 on 2022-05-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_section_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('first_section_title', models.CharField(blank=True, max_length=255, null=True)),
                ('first_section_subtitle_title', models.CharField(blank=True, max_length=255, null=True)),
                ('first_section_first_paragraph', models.TextField(blank=True, null=True)),
                ('first_section_second_paragraph', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MainSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('bio', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecondSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_section_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('second_section_title', models.CharField(blank=True, max_length=255, null=True)),
                ('second_section_subtitle_title', models.CharField(blank=True, max_length=255, null=True)),
                ('second_section_first_paragraph', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
